plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.fly.motion"
    compileSdk = 35
    ndkVersion = "28.2.13676358"
    buildToolsVersion = "35.0.1" // KOREKSI 1: Menghapus tanda kutip ganda berlebih

    defaultConfig {
        applicationId = "com.fly.motion"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        externalNativeBuild {
            cmake {
                // KOREKSI 2: Sintaks Kotlin DSL menggunakan fungsi kurung (), bukan spasi
                cppFlags("-std=c++17") 
                
                // KOREKSI 3: abiFilters di Kotlin adalah MutableSet, gunakan .add() atau +=
                abiFilters.add("arm64-v8a") 
            }
        }
    }

    buildFeatures {
        viewBinding = true
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            // KOREKSI 4: Versi CMake "4.1.1" sepertinya salah (terlalu tinggi/tidak ada).
            // Android biasanya menggunakan "3.18.1", "3.22.1", dll.
            // Hapus baris ini untuk menggunakan default, atau gunakan versi yang terinstal.
            version = "4.1.1" 
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            // KOREKSI 5: Cara penulisan JvmTarget yang lebih standar dan aman
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
}
